env:
  global:
    - "RUST_PATH=$HOME/.rust/lib"
    - secure: MNwmpnZcX2uigKGqJll7L2XmZ8u/gwRJyWtCoL1uy3H3lclU9b+62RiyScYjvZ/zN1eZo2fdKwNhTLJ2qP0VX20Vgvup7kqB2cEmF6RflcuTF+kUwjvVsnzoTYKoDFkI0pZtAVCyLnDIyyjKd2SrwrErntw77z4rxwbDd54YN9U=
before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
  - sudo pip install cargo-lite
  - bash .install_glfw.sh
script:
  - echo $RUST_PATH
  - cargo-lite install
  - rustdoc src/lib.rs
  - cargo-lite install http://github.com/bjz/glfw-rs.git
  - rustc src/examples/triangle.rs
  - rustc src/examples/texture.rs
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
